/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Result of the clear request for this monitor, identified by its Id.
 *
 *
 */
export type ClearMonitoringStatusEnumType = "Accepted" | "Rejected" | "NotFound";

export interface ClearVariableMonitoringResponse {
  customData?: CustomDataType;
  clearMonitoringResult: ClearMonitoringResultType[];
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ClearMonitoringResultType {
  customData?: CustomDataType;
  status: ClearMonitoringStatusEnumType;
  /**
   * Id of the monitor of which a clear was requested.
   *
   *
   */
  id: number;
  statusInfo?: StatusInfoType;
}
/**
 * Element providing more information about the status.
 *
 */
export interface StatusInfoType {
  customData?: CustomDataType;
  /**
   * A predefined code for the reason why the status is returned in this response. The string is case-insensitive.
   *
   */
  reasonCode: string;
  /**
   * Additional text to provide detailed information.
   *
   */
  additionalInfo?: string;
}
