/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines whether certificate needs to be installed or updated.
 *
 */
export type CertificateActionEnumType = "Install" | "Update";

export interface Get15118EVCertificateRequest {
  customData?: CustomDataType;
  /**
   * Schema version currently used for the 15118 session between EV and Charging Station. Needed for parsing of the EXI stream by the CSMS.
   *
   *
   */
  iso15118SchemaVersion: string;
  action: CertificateActionEnumType;
  /**
   * Raw CertificateInstallationReq request from EV, Base64 encoded.
   *
   */
  exiRequest: string;
}
/**
 * This class does not get 'AdditionalProperties = false' in the schema generation, so it can be extended with arbitrary JSON properties to allow adding custom data.
 */
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
