on: ["push","pull_request"]

name: Test Coveralls

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVer:
          - 17.3.0
          - 18
          - 19
    steps:

      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.nodeVer }}

      - name: Run tests
        run: |
          npm ci
          npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
